Add Error Message via Toastify
neuefische/cgn-java-22-2-zoomanagement pull request #26
Opened 2022-07-30 23:08 UTC by irenepapaspyratos

2022-08-01 16:28 UTC, Flooooooooooorian requested changes

2022-08-01 16:28 UTC, Flooooooooooorian commented on frontend/src/animal/AddAnimal.tsx
> +        setAnimalName("");
```suggestion
        props.addAnimal(animalName)
        .then(() => setAnimalName(""))
            .catch((error) => {
                notify("Hi sorrry!!! " + error.message)
            })
```

2022-08-01 16:28 UTC, Flooooooooooorian commented on frontend/src/animal/useAnimals.ts
> +            .then(getAnimalList)
Nutz entweder async/await oder .then()

2022-08-02 07:21 UTC, danielschwarz-neuefische commented on frontend/src/animal/useAnimals.ts
> +            .then(getAnimalList)
Bitte vorerst kein async/await, damit das auch jeder aus den anderen Gruppen versteht.

2022-08-03 08:09 UTC, Flooooooooooorian submitted a review, later dismissed

2022-08-03 08:09 UTC, Flooooooooooorian commented on backend/src/main/resources/application.properties
> +spring.data.mongodb.uri=mongodb+srv://tetratolog:cPjMHFk0s6fVBc2p@cluster0.rojxi.mongodb.net/?retryWrites=true&w=majority
gehört nicht zu diesem Ticket, zudem willst du wahrscheinlich nicht das deine Zugangsdaten für die Datenbank jetzt öffentlich im Internet sind 😬

2022-08-03 12:31 UTC, Flooooooooooorian approved these changes

2022-08-03 12:31 UTC, merged