add deleteTruck
neuefische/cgn-java-22-2-zoomanagement pull request #32
Opened 2022-08-01 15:06 UTC by KSVoss

2022-08-08 06:40 UTC, bartfastiel requested changes
Habe es mir noch nicht im Detail angesehen, aber SonarCloud hat noch zwei Punkte gemeldet:
* Es gibt einen Bug (Namensgebung)
* Der neue Backend-Code ist noch ungetestet

2022-08-08 09:35 UTC, mboosch commented
Added ControllerTest, renamed GetAllTrucks, should be ready to merge.

2022-08-09 08:06 UTC, YA2323 commented on frontend/src/truck/AddTruck.tsx
> -        event.preventDefault()
props.addtruck wurde gelöscht, wie schickt ihr den TruckNamen?

2022-08-09 08:11 UTC, YA2323 commented on frontend/src/truck/useTrucks.ts
> +            .catch(error => notify("existiert nicht"));
Der error im catch wird niemals benutzt

2022-08-09 08:16 UTC, alanmiste commented on frontend/src/truck/useTrucks.ts
> +            .catch(error => notify("existiert nicht"));
`.catch( error => {
                    toast.error(error.message, {
                            position: toast.POSITION.TOP_LEFT
                        }
                    )
                })`

2022-08-12 10:39 UTC, merged