deletePlants
neuefische/cgn-java-22-2-zoomanagement pull request #38
Opened 2022-08-03 15:49 UTC by BarburKoeroglu

2022-08-05 13:17 UTC, alanmiste requested changes, later dismissed

2022-08-05 13:17 UTC, alanmiste commented on backend/src/test/java/de/neuefische/cgnjava222/zoomanagement/zoo/plant/PlantControllerTest.java
> +import org.springframework.test.annotation.DirtiesContext;
DirtiesContext ist nicht für UnitTest, wird ebenfalls nicht benutzt.

2022-08-05 13:17 UTC, alanmiste commented on backend/src/test/java/de/neuefische/cgnjava222/zoomanagement/zoo/plant/PlantServiceTest.java
> +        doNothing().when(testPlantRepo).deleteById(any(String.class));
Verbesserungsvorschlag:
Ihr könnt anstatt String.class eine Id nutzen.

2022-08-05 13:17 UTC, alanmiste commented on frontend/src/plant/Plant.tsx
> +}
Bitte noch einen Zeilenumbruch.

2022-08-08 08:06 UTC, AccessCoder approved these changes
lgtm

2022-08-08 08:07 UTC, AccessCoder approved these changes
lgtm

2022-08-08 08:09 UTC, merged