Animal positioning
neuefische/cgn-java-22-2-zoomanagement pull request #45
Opened 2022-08-04 15:20 UTC by alanmiste

2022-08-05 12:55 UTC, BarburKoeroglu commented on backend/src/main/java/de/neuefische/cgnjava222/zoomanagement/zoo/animal/Animal.java
> +public record Animal(@Id String id, String name, Position position) {
sieht gut aus!

2022-08-05 13:18 UTC, alanmiste commented on backend/src/main/java/de/neuefische/cgnjava222/zoomanagement/zoo/animal/Animal.java
> +public record Animal(@Id String id, String name, Position position) {
Danke :)

2022-08-05 13:27 UTC, BarburKoeroglu commented on backend/src/main/java/de/neuefische/cgnjava222/zoomanagement/zoo/animal/AnimalService.java
> +    public Animal addAnimalPosition(Animal animalWithPosition) {
updateAnimalPosition zeigt klarer, was die Intention ist. Ansonsten ist die Funktion gut.

2022-08-05 14:01 UTC, BarburKoeroglu commented on frontend/src/animal/AnimalDetails.tsx
> +}
Leerzeile hinter der letzten Klammer

2022-08-05 14:02 UTC, BarburKoeroglu commented on frontend/src/animal/Animal.ts
> +}
Leerzeile hinter der letzten Klammer

2022-08-05 14:03 UTC, BarburKoeroglu commented on frontend/src/animal/AnimalList.tsx
> +}
Leerzeile hinter der letzten Klammer

2022-08-05 14:38 UTC, BarburKoeroglu commented on frontend/src/animal/AnimalListItem.tsx
> +                navigate(`/${props.animal.id}`)
in der Ticketbeschreibung wird ein anderer Aufbau der URL gefordert: /#/animals/animalId

2022-08-05 14:50 UTC, BarburKoeroglu commented on frontend/src/animal/useAnimals.ts
> +        const newAnimalWithXY: Animal = {
Variablenname ist für Themenfremde nicht sofort klar; newAnimalWithPosition zeigt deutlicher was gemeint ist

2022-08-05 15:21 UTC, BarburKoeroglu requested changes
Gute Arbeit! Der Punkt bzgl. der URL muss noch angepasst werden. Alle anderen Punkte sind optional. Liebe Grüße

2022-08-08 10:24 UTC, mboosch submitted a review, later dismissed
Sieht gut aus.

2022-08-12 08:00 UTC, Flooooooooooorian commented on backend/src/main/java/de/neuefische/cgnjava222/zoomanagement/zoo/animal/AnimalService.java
> +        animalRepo.deleteById(animalWithPosition.id());
```suggestion
```

2022-08-12 08:00 UTC, Flooooooooooorian commented on backend/src/main/java/de/neuefische/cgnjava222/zoomanagement/zoo/animal/AnimalService.java
> +        return animalWithPosition;
```suggestion
        return animalRepo.save(animalWithPosition);
```

2022-08-12 08:26 UTC, merged